Algoritmo "problema consumo"
          //nesse caso poderiamo utilizar uma regra de três pra saber como resolveriamos o "problema"
Var

   distancia, combustivel, consumo : real

Inicio
      
       escreva("Distancia percorrida: ")
       leia (distancia)
       escreva ("Combustível gasto:: ")
       leia (combustivel)

       consumo <- distancia / combustivel

       escreva ("Consumo médio = ",consumo:8:3)

Fimalgoritmo